import { Assignment, Course, CalEvent, User } from './types';

export const ASSIGNMENTS_DEFAULT: Record<string, Assignment> = {
  a1: {
    id: 'a1',
    title: 'Database Design HW3',
    course: 'CS301',
    courseName: 'Database Systems',
    due: 'Feb 21, 2026',
    dueDate: new Date(2026, 1, 21),
    points: 100,
    type: 'Homework',
    status: 'open',
    file: null,
    instructor: { name: 'Dr. Somchai P.', title: 'Associate Professor' }
  },
  a2: {
    id: 'a2',
    title: 'SE Project Report',
    course: 'SE201',
    courseName: 'Software Engineering',
    due: 'Feb 24, 2026',
    dueDate: new Date(2026, 1, 24),
    points: 50,
    type: 'Report',
    status: 'open',
    file: null,
    instructor: { name: 'Asst.Prof. Nipa K.', title: 'Instructor' }
  },
  a3: {
    id: 'a3',
    title: 'Algo Problem Set 4',
    course: 'CS401',
    courseName: 'Algorithms',
    due: 'Mar 1, 2026',
    dueDate: new Date(2026, 2, 1),
    points: 80,
    type: 'Problem Set',
    status: 'open',
    file: null,
    instructor: { name: 'Dr. Wiroj T.', title: 'Associate Professor' }
  },
  a4: {
    id: 'a4',
    title: 'English Essay Draft',
    course: 'ENG101',
    courseName: 'English for Tech',
    due: 'Feb 28, 2026',
    dueDate: new Date(2026, 1, 28),
    points: 30,
    type: 'Essay',
    status: 'submitted',
    submittedOn: 'Feb 17, 2026',
    file: 'essay_draft.pdf',
    instructor: { name: 'Aj. Malee S.', title: 'Lecturer' }
  },
  a5: {
    id: 'a5',
    title: 'Database HW2',
    course: 'CS301',
    courseName: 'Database Systems',
    due: 'Feb 10, 2026',
    dueDate: new Date(2026, 1, 10),
    points: 100,
    type: 'Homework',
    status: 'submitted',
    submittedOn: 'Feb 10, 2026',
    file: 'db_hw2.pdf',
    instructor: { name: 'Dr. Somchai P.', title: 'Associate Professor' }
  },
  a6: {
    id: 'a6',
    title: 'Algo Problem Set 3',
    course: 'CS401',
    courseName: 'Algorithms',
    due: 'Feb 11, 2026',
    dueDate: new Date(2026, 1, 11),
    points: 80,
    type: 'Problem Set',
    status: 'late',
    submittedOn: 'Feb 12, 2026',
    file: 'algo_ps3.pdf',
    instructor: { name: 'Dr. Wiroj T.', title: 'Associate Professor' }
  },
  a7: {
    id: 'a7',
    title: 'SE Requirements Doc',
    course: 'SE201',
    courseName: 'Software Engineering',
    due: 'Feb 5, 2026',
    dueDate: new Date(2026, 1, 5),
    points: 50,
    type: 'Document',
    status: 'submitted',
    submittedOn: 'Feb 5, 2026',
    file: 'se_req.docx',
    instructor: { name: 'Asst.Prof. Nipa K.', title: 'Instructor' }
  },
  a8: {
    id: 'a8',
    title: 'Network Lab Report',
    course: 'NET201',
    courseName: 'Computer Networks',
    due: 'Feb 26, 2026',
    dueDate: new Date(2026, 1, 26),
    points: 60,
    type: 'Lab Report',
    status: 'open',
    file: null,
    instructor: { name: 'Dr. Prasert M.', title: 'Associate Professor' }
  },
  a9: {
    id: 'a9',
    title: 'Discrete Math HW2',
    course: 'MATH301',
    courseName: 'Discrete Math',
    due: 'Feb 25, 2026',
    dueDate: new Date(2026, 1, 25),
    points: 40,
    type: 'Homework',
    status: 'open',
    file: null,
    instructor: { name: 'Dr. Chaiwat B.', title: 'Associate Professor' }
  },
};

export const COURSES: Record<string, Course> = {
  cs301: {
    code: 'CS301',
    name: 'Database Systems',
    icon: 'Database',
    credits: 3,
    color: '#7c3d3d',
    instructor: 'Dr. Somchai P.',
    room: 'ENG-201',
    schedule: 'Mon/Wed 09:00–10:30',
    assignments: ['a1', 'a5'],
    midterm: 'Mar 3, 2026',
    final: 'Apr 5, 2026'
  },
  se201: {
    code: 'SE201',
    name: 'Software Engineering',
    icon: 'Settings',
    credits: 3,
    color: '#c17b4e',
    instructor: 'Asst.Prof. Nipa K.',
    room: 'ENG-305',
    schedule: 'Tue/Thu 10:00–11:30',
    assignments: ['a2', 'a7'],
    midterm: 'Mar 5, 2026',
    final: 'Apr 7, 2026'
  },
  cs401: {
    code: 'CS401',
    name: 'Algorithms',
    icon: 'Calculator',
    credits: 3,
    color: '#4a6fa5',
    instructor: 'Dr. Wiroj T.',
    room: 'SCI-101',
    schedule: 'Mon/Fri 13:00–14:30',
    assignments: ['a3', 'a6'],
    midterm: 'Mar 8, 2026',
    final: 'Apr 9, 2026'
  },
  eng101: {
    code: 'ENG101',
    name: 'English for Tech',
    icon: 'FileText',
    credits: 2,
    color: '#4a8c6f',
    instructor: 'Aj. Malee S.',
    room: 'HUM-102',
    schedule: 'Wed 14:00–16:00',
    assignments: ['a4'],
    midterm: 'Mar 10, 2026',
    final: 'Apr 11, 2026'
  },
  math301: {
    code: 'MATH301',
    name: 'Discrete Math',
    icon: 'Ruler',
    credits: 3,
    color: '#9b59b6',
    instructor: 'Dr. Chaiwat B.',
    room: 'SCI-203',
    schedule: 'Tue/Thu 13:00–14:30',
    assignments: ['a9'],
    midterm: 'Mar 12, 2026',
    final: 'Apr 13, 2026'
  },
  net201: {
    code: 'NET201',
    name: 'Computer Networks',
    icon: 'Globe',
    credits: 3,
    color: '#e67e22',
    instructor: 'Dr. Prasert M.',
    room: 'ENG-106',
    schedule: 'Mon/Wed 15:00–16:30',
    assignments: ['a8'],
    midterm: 'Mar 15, 2026',
    final: 'Apr 15, 2026'
  },
};

export const CAL_EVENTS: Record<string, CalEvent[]> = {
  '2026-1-21': [{ name: 'Database Design HW3 Due', type: 'assign', aid: 'a1' }],
  '2026-1-24': [{ name: 'SE Project Report Due', type: 'assign', aid: 'a2' }],
  '2026-1-25': [{ name: 'Discrete Math HW2 Due', type: 'assign', aid: 'a9' }],
  '2026-1-26': [{ name: 'Network Lab Report Due', type: 'assign', aid: 'a8' }],
  '2026-1-28': [{ name: 'English Essay Draft Due', type: 'assign', aid: 'a4' }],
  '2026-2-1': [{ name: 'Algo Problem Set 4 Due', type: 'assign', aid: 'a3' }],
  '2026-2-3': [{ name: 'CS301 Midterm – Room A101', type: 'midterm', cid: 'cs301' }],
  '2026-2-5': [{ name: 'SE201 Midterm – Room B203', type: 'midterm', cid: 'se201' }],
  '2026-2-8': [{ name: 'CS401 Midterm – SCI-101', type: 'midterm', cid: 'cs401' }],
  '2026-2-10': [{ name: 'ENG101 Midterm – HUM-102', type: 'midterm', cid: 'eng101' }],
  '2026-2-12': [{ name: 'MATH301 Midterm – SCI-203', type: 'midterm', cid: 'math301' }],
  '2026-2-15': [{ name: 'NET201 Midterm – ENG-106', type: 'midterm', cid: 'net201' }],
  '2026-3-5': [{ name: 'CS301 Final Exam', type: 'exam', cid: 'cs301' }],
  '2026-3-7': [{ name: 'SE201 Final Exam', type: 'exam', cid: 'se201' }],
  '2026-3-9': [{ name: 'CS401 Final Exam', type: 'exam', cid: 'cs401' }],
  '2026-3-11': [{ name: 'ENG101 Final Exam', type: 'exam', cid: 'eng101' }],
  '2026-3-13': [{ name: 'MATH301 Final Exam', type: 'exam', cid: 'math301' }],
  '2026-3-15': [{ name: 'NET201 Final Exam', type: 'exam', cid: 'net201' }],
};

export const UNIVERSITY_DB: Record<string, User & { password?: string }> = {
  '6500000001': { id: '6500000001', name: 'Giselle Moonbin', password: 'password123', dept: 'Software Engineering' },
  '6500000002': { id: '6500000002', name: 'Methaporn Apiwasuchai', password: 'abcd1234', dept: 'Computer Science' },
  '6500000003': { id: '6500000003', name: 'Chompunut Namkort', password: 'test1234', dept: 'Information Technology' },
};
